server:
  port: 8080


---
spring:
  profiles: default
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:a6aa9a549f08211e99966069ce967329-143809391.ap-northeast-2.elb.amazonaws.com:3306}/${DATASORUCE_TABLESPACE:my-database}
    username: ${DATASORUCE_USERNAME:root}
    password: ${DATASORUCE_PASSWORD:secretpassword}
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        type: trace        

server:
  port: 8083
---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    consumer:
      enable-auto-commit: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:a6aa9a549f08211e99966069ce967329-143809391.ap-northeast-2.elb.amazonaws.com:3306}/${DATASORUCE_TABLESPACE:my-database}
    username: ${DATASORUCE_USERNAME:root}
    password: ${DATASORUCE_PASSWORD:secretpassword}
    driverClassName: com.mysql.cj.jdbc.Driver