spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:a6aa9a549f08211e99966069ce967329-143809391.ap-northeast-2.elb.amazonaws.com:3306}/${DATASORUCE_TABLESPACE:my-database}
    username: ${DATASORUCE_USERNAME:root}
    password: ${DATASORUCE_PASSWORD:secretpassword}
    driverClassName: com.mysql.cj.jdbc.Driver

# --- server
server:
  port: 8090

---
spring:
  profiles: docker
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://${DATASORUCE_ADDRESS:a6aa9a549f08211e99966069ce967329-143809391.ap-northeast-2.elb.amazonaws.com:3306}/${DATASORUCE_TABLESPACE:my-database}
    username: ${DATASORUCE_USERNAME:root}
    password: ${DATASORUCE_PASSWORD:secretpassword}
    driverClassName: com.mysql.cj.jdbc.Driver


