server:
  port: 8080


topic:
  topicName: topic


---
spring:
  profiles: default
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
#    password: secretpassword
  cache:
    redis:
      cache-null-values: false
      use-key-prefix: true
    type: redis

logging:
  level:
    org:
      hibernate:
        type: trace        

server:
  port: 8081
---
spring:
  profiles: docker
  kafka:
    bootstrap-servers: my-kafka.kafka.svc.cluster.local:9092
    consumer:
      enable-auto-commit: true
